settings:
  title: 'PikaOS Status'
  url: 'https://status.pika-os.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: pikaos-website # unique identifier
    name: PikaOS Site
    description: 'The website for Pika OS' # default=empty
    url: 'https://pika-os.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: ppa-pika-os-com
    name: ppa-pika-os-com
    description: 'Package repo for PikaOS'
    url: 'https://ppa.pika-os.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

  - id: iso-pika-os-com
    name: iso-pika-os-com
    description: 'ISO repo for PikaOS'
    url: 'https://iso.pika-os.com'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true
