name = "cf-svelte-ts-pika"
workers_dev = true
main = "./.cloudflare/worker.mjs"
site.bucket = "./.cloudflare/public"
compatibility_date = "2023-04-19"
node_compat = true

[durable_objects]
bindings = [{name = "EUWEST", class_name = "EUWestObject"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["EUWestObject"]

[triggers]
crons = ["* * * * *"]
