name = "cf-svelte-ts-pika"
workers_dev = true
main = "./.cloudflare/worker.mjs"
site.bucket = "./.cloudflare/public"
compatibility_date = "2023-04-19"
node_compat = true

[triggers]
crons = ["* * * * *"]

[env.production]
