name = "cf-workers-pika-status-page"
workers_dev = true
compatibility_date = "2022-07-12"
main = "index.js"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"

#[build]
#command = "npm run build"
# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
