name = "cf-workers-status-pagee"
workers_dev = true
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"
main = "index.js"

[triggers]
crons = ["* * * * *"]

[site]
bucket = "out"

# uncomment and adjust following if you are not using GitHub Actions
#[env.production]
#kv-namespaces = [{binding="KV_STATUS_PAGE", id="xxxx", preview_id=""}]
#zone_id="xxx"
#route="xxx"
